name: Deploy to Docker Hub

on:
  push:
    branches:
      - main  # Change this to your main branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        env:
          DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: |
          docker build --file Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/my-flask-app:${{ github.sha }} .
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_UDSERNAME }}/my-flask-app:${{ github.sha }}
