name: Deploy to Docker Hub

on:
  push:
    branches:
      - main  # Change this to your main branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/my-flask-app:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_UDSERNAME }}/my-flask-app:${{ github.sha }}
